apiVersion: v1
kind: Secret
metadata:
 name: docker-credential
 namespace: default
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJICJhdXRoIjogIlpHeGphM04zYmpNek5EcHNaV1ZqYWpBNE1EUWgiCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiCn0K"
type: kubernetes.io/dockerconfigjson
