apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: polling-operator-role
  namespace: default # insert namespace you need to grant access to
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polling-operator-cluster-role
subjects:
- kind: ServiceAccount
  name: tekton-polling-operator
  namespace: default # insert the namespace you deployed the operator in