apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  namespace: default
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: jalju0804
  password: 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 # github에서 토큰을 만들어서 가져와야됨